### ISSUE TITLE
wallpapers for China and the world

### ISSUE THREAD

**Issue by ltdragonfly** [smloli/BingWallpaperDownload#1]
Is there any difference between the themes of bing everyday wallpaper for China and the world?
In my memory, the pictures are different on some particular days.

**Comment by smloli** [comment]
On certain festivals, the wallpaper will be different

**Comment by ltdragonfly** [comment]
the newly release one is killed by 360 antivirus...

**Comment by smloli** [comment]
The golang program is very easy to be checked and killed by anti-virus software recently, you can also download the source code and compile it yourself
