### ISSUE TITLE
ubuntu vps   go run main.go  找不到 下载 路径 

### ISSUE THREAD

**Issue by hello1983** [smloli/BingWallpaperDownload#2]
找不到 下载 路径     请问 下载到了 那个文件夹

**Comment by smloli** [comment]
`package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Dir(os.Args[0]) + filepath.FromSlash("/") + "wallpaper" + filepath.FromSlash("/"))
}`
将这段代码保存为main.go 然后编译 再以你之前运行BingWallpaperDownload-linux-amd64的方式运行它 就可以看到下载的位置了

**Comment by smloli** [comment]
> 找不到 下载 路径 请问 下载到了 那个文件夹

package main

import (
"fmt"
"os"
"path/filepath"
)

func main() {
fmt.Println(filepath.Dir(os.Args[0]) + filepath.FromSlash("/") + "wallpaper" + filepath.FromSlash("/"))
}

将这段代码保存为main.go 然后编译 再以你之前运行BingWallpaperDownload-linux-amd64的方式运行它 就可以看到下载的位置了
